# Generated by Django 3.1.2 on 2022-01-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_id', to='stock.stock'),
        ),
    ]
