# Generated by Django 3.1.2 on 2022-01-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='total_purchase_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
