# Generated by Django 3.1.2 on 2022-01-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_leaderboard_points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='Point',
        ),
    ]
