# Generated by Django 3.1.2 on 2022-02-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20220131_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
