# Generated by Django 3.1.2 on 2022-02-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20220217_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='twitter_handle',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
